export const currencyData = [
  'AUD - Australia',
  'BGN - Bulgaria',
  'CAD - Canada',
  'HRK - Croatia',
  'CZK - Czech Republic',
  'DKK - Denmark',
  'EUR - Europe (all SEPA countries)',
'HKD - Hong Kong',
'HUF - Hungary',
'INR - India',
'IDR - Indonesia',
'JPY - Japan',
'MYR - Malaysia',
'NZD - New Zealand',
'NOK - Norway',
'PLN - Poland',
'RON - Romania',
'SGD - Singapore',
'SEK - Sweden',
'CHF - Switzerland and Liechtenstein',
'TRY - Turkey',
'AED - United Arab Emirates',
'GBP - United Kingdom',
'USD -United States of America'
]